### ISSUE TITLE
Adding class for checkbox label does not work

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [tobimori/kirby-dreamform#107]
The class `my-checkbox-label` is not added to the html.

```php
<?php snippet('dreamform/form', [
  'form' => $block->form()->toPage(),
  'attr' => [
    'checkbox' => [
      'label' => [
        'class' => 'my-checkbox-label'
      ]
    ]
  ]
]); ?>
```

Seems to be an issue in [this line](https://github.com/tobimori/kirby-dreamform/blob/develop/snippets/fields/checkbox.php#L41).

**Comment by tobimori** [comment]
```php
<?php snippet('dreamform/form', [
  'form' => $block->form()->toPage(),
  'attr' => [
    'checkbox' => [
      'value' => [
        'class' => 'my-checkbox-label'
      ]
    ]
  ]
]); ?>
```

Can you try this?

**Comment by SebastianEberlein-JUNO** [comment]
Yes, this works. I thought `label` refers to the `<label>` of each `<input type="checkbox">`.

We usually wrap multiple checkboxes in a `<fieldset>` and use a `<legend>` to label all checkboxes.

**Comment by tobimori** [comment]
I totally agree with you on that, iirc I named it differently since they can have a field label and I wanted to avoid the field label styles be applied with that. I will consider moving the checkbox/radio fields to fieldset + legend for that in 2.0.
