### ISSUE TITLE
Compatibility with Kirby 5

### ISSUE THREAD

**Issue by Onyxmoon** [tobimori/kirby-dreamform#111]
Thank you for this plugin. Considering the release of Kirby 5 in early 2025, compatibility should be checked. 

When is the release of this adaptions planned as many new pages are already being developed on Kirby 5 😇? This is no PR, because I don't know in which release this is planned.

**Comment by tobimori** [comment]
Yes, you can download the current develop branch. Be aware there might sitll be some breaking changes until the full release of DreamForm 2.0.
