### ISSUE TITLE
Implement custom error message when sender email is empty ("" is not a valid email address)

### ISSUE THREAD

**Issue by medienbaecker** [tobimori/kirby-dreamform#25]
I just can't seem to get this plugin to work.

No matter what I do, after I add the `email` action I get an error `"" is not a valid email address`. It doesn't matter if I choose "static" or "from user input" in the action block. The email address doesn't seem to matter either. Once I remove the block it works (the submission in the panel).

![CleanShot 2024-04-08 at 15 52 33@2x](https://github.com/tobimori/kirby-dreamform/assets/7975568/b714a32d-efc0-48f6-99df-6f86b1c74e77)

![CleanShot 2024-04-08 at 16 08 55@2x](https://github.com/tobimori/kirby-dreamform/assets/7975568/11c5b8e8-d0de-430b-b4fb-8f67215e86db)

**Comment by tobimori** [comment]
As mentioned on Discord, this is related to the sender email address. By default, the plugin falls back to the `email.transport.username` option. 
If you're experiencing this, you might have to explicitely specify an email address using the following config:

```php
<?php

return [
  'tobimori.dreamform.actions.email' => [
    'from' => [
      'email' => 'xxx@example.com'
      'name' => 'Sender Name'
    ]
  ]
];
 ```
