### ISSUE TITLE
Form snippet not working with Blade templating

### ISSUE THREAD

**Issue by samlinck** [tobimori/kirby-dreamform#37]
Error location:
/var/www/html/site/plugins/kirby-dreamform/snippets/fields/partials/wrapper.php

When I follow the instructions from [Using Forms](https://plugins.andkindness.com/dreamform/docs/setup/using-forms)
I get **Undefined variable $slot **.

**Comment by samlinck** [comment]
Hi I don't have much more info except that I used your snippet in a blade file after going to the installation as described in the docs. If I go into the plugin and comment that part, I can submit the form as expected.

**Comment by tobimori** [comment]
The included form snippets use slots: https://getkirby.com/docs/guide/templates/snippets#passing-slots-to-snippets
I think the issue in this case is on the Blade template engine.

**Comment by tobimori** [comment]
I've sent you a message on Discord, maybe we can work it out together.

**Comment by tobimori** [comment]
I made a PR to the Blade repo that should fix the issue: https://github.com/lukasleitsch/kirby-blade/pull/35 - please test it and let me know if it works!
