### ISSUE TITLE
Form snippet doesn't work with Twig templates

### ISSUE THREAD

**Issue by skraby** [tobimori/kirby-dreamform#41]
Hello, I use [Twig plugin](https://github.com/wearejust/kirby-twig) on my Kirby projects and recently I tried to use your plugin. There is a issue with slots: snippet throws error "**Undefined variable $slot **". 
It seems similar to [#37](https://github.com/tobimori/kirby-dreamform/issues/37).

Could you point me to a solution?

**Comment by tobimori** [comment]
Hi!

Please try this PR and see if it fixes the issue: https://github.com/wearejust/kirby-twig/pull/3

**Comment by skraby** [comment]
It works, thank you 😃
