### ISSUE TITLE
Edge cases when using multiple forms on the same page

### ISSUE THREAD

**Issue by animaux** [tobimori/kirby-dreamform#51]
If I am not missing the obvious and that’s already possible — it would be nice if the page scrolls to the form and/or the error-/success-messages after submit. Otherwise it’s easy to miss submission errors (on longer pages where the form is further down).

Obviously this would be easy with a #-link, but I have no idea how to implement this, and hardcoding an URL is not an option.

**Comment by tobimori** [comment]
Please use HTMX or API submissions for this.

**Comment by animaux** [comment]
:(

**Comment by tobimori** [comment]
Right now, I don't really know how to solve this technically and capture all edge cases. (Mostly related on how to solve this without a breaking change)

I will have to investigate and make a clear decision on what is supported and what not.

**Comment by animaux** [comment]
Thanks!

**Comment by tobimori** [comment]
I implemented this in the latest commit.
