### ISSUE TITLE
Email action does not work with file field in form

### ISSUE THREAD

**Issue by tobimori** [tobimori/kirby-dreamform#55]

**Comment by mikewink** [comment]
Experiencing this problem with HTMX support active and not active.

```
Kirby\Toolkit\Str::esc(): Argument #1 ($string) must be of type string, array given, called in /var/www/html/kirby/config/methods.php on line 346
```

I am using the email action with, together with the default template.

**Comment by tobimori** [comment]
Yep, thanks for confirming. Sorry, I couldn't get around to fix it yet. A temporary option would be to provide a custom email template that does not include the file field. You'll be able to download the uploaded files from the panel.
