### ISSUE TITLE
Numbers as values are not read correctly

### ISSUE THREAD

**Issue by sciloqi** [tobimori/kirby-dreamform#62]
First of all, great plugin!

I made a set of radio buttons for a 5-star rating system: Value for the first option is "1", label is "⭐️", and so on... 

Answers (values) are correct stored in the content files, but not displayed in the structure field in the panel as answers (empty column).

The other way round, value is "⭐️" and label is "1", it works. 

![Bildschirmfoto 2024-06-12 um 12 53 19](https://github.com/tobimori/kirby-dreamform/assets/23317040/cfd2ff58-9041-4b18-8503-4cd694b10631)

<img width="754" alt="Bildschirmfoto 2024-06-12 um 12 55 03" src="https://github.com/tobimori/kirby-dreamform/assets/23317040/956e9c9e-beb9-489e-a9f6-ea1b983a5d66">

**Comment by tobimori** [comment]
When clicking on an answer, they are correctly shown, right?

**Comment by tobimori** [comment]
I assume Kirby has trouble parsing the answer as raw value

**Comment by sciloqi** [comment]
> When clicking on an answer, they are correctly shown, right?

no, they are not shown... none of the options is marked

![Bildschirmfoto 2024-06-12 um 14 33 51](https://github.com/tobimori/kirby-dreamform/assets/23317040/6b0f47fa-7456-48f7-82b1-67091fa7d559)

**Comment by tobimori** [comment]
I think I managed to fix it, can you try applying the change from the commit manually?

**Comment by sciloqi** [comment]
Yes, works as expected! 

The value "1" is shown in the structure field, and the right option is marked!
