### ISSUE TITLE
Scroll to success message in HTMX mode

### ISSUE THREAD

**Issue by medienbaecker** [tobimori/kirby-dreamform#64]
How do you scroll to the success message on long pages with forms when using the HTMX mode? Do I have to hook into HTMX's events?

**Comment by tobimori** [comment]
When HTMX mode is enabled, the user should stay at the same location as when they pressed the submit button.

**Comment by medienbaecker** [comment]
Yes, but then the success message is probably shorter than the form and the user ends up at the bottom of the page. For example this form is relatively long: https://verlagegegenrechts.de/materialien

**Comment by tobimori** [comment]
Can you test if this change works? https://github.com/tobimori/kirby-dreamform/commit/3330c040baf95842c03ec33256ad7bb4fedd8f24

**Comment by medienbaecker** [comment]
Maybe related, defining an `hx-indicator` also means I have to use a custom form snippet, correct?

**Comment by tobimori** [comment]
If you want a spinner in the button, you'd create a custom button snippet in `site/snippets/dreamform/fields/button.php` and then add the hx-indicator attribute to the form element via the `dreamform/form` snippet call.

**Comment by medienbaecker** [comment]
That works, but shouldn't it also scroll to the top when there's an error message (above the form)?

**Comment by tobimori** [comment]
With the change it should always scroll to the top, so even when an error happens.

**Comment by tobimori** [comment]
![CleanShot 2024-06-19 at 11 52 51@2x](https://github.com/tobimori/kirby-dreamform/assets/29142128/cbd9c1bd-24cf-4510-a92c-d3f879550593)

You could also add the indicator via CSS/pseudo elements controlled via the `htmx-request` class on the form element.

**Comment by medienbaecker** [comment]
I think you want `show:top` instead.

**Comment by tobimori** [comment]
Switched to `show:top`, will close for now since that's solved. Thanks!

**Comment by medienbaecker** [comment]
Awesome, thank you.
