### ISSUE TITLE
Feature: standard HTML5-fields

### ISSUE THREAD

**Issue by derStephan** [tobimori/kirby-dreamform#78]
Hi, 

thanks for dreamform, works pretty well for us. I suggest to add all [HTML 5 standard inputs ](https://www.w3schools.com/tags/tag_input.asp)like time or date or password or range. 

Now I have to use text fields without any validation or a custom field which is much slower to create.

Thank you in advance.

Stephan

**Comment by tobimori** [comment]
Please create separate feature discussions for each field that you need. If they get enough upvotes, I'll add them when I find the time. A "input type" dropdown won't be added and goes against the philosophy of DreamForm.
