### ISSUE TITLE
Feature: Possibility to add client-site restrictions to the fields

### ISSUE THREAD

**Issue by derStephan** [tobimori/kirby-dreamform#79]
Hi,

it would be perfect if we could have some setting to add client-site restrictions to the field. 

for example: ``max="10"`` or ``pattern="[123]-[456]"`` or ``step=".01"``

I am aware that this is no security feature but it may be helpful for the people entering data. And if the security risk is too high for your taste, you could check that these restrictions are met on the server after transmission of the form. But that may be too much to ask. 

thanks in advance
Stephan

**Comment by tobimori** [comment]
- Fields like the Numbers field already support min / max / step values (which are also checked on the backend)
- For patterns, please create a custom field that has a hard-coded pattern.

One core UX pillar of DreamForm is to make it as easy as possible for non-technical people to create forms. A regex pattern field is certainly not that.

**Comment by derStephan** [comment]
> One core UX pillar of DreamForm is to make it as easy as possible for non-technical people to create forms

That contradicts the approach of creating costum fields for everything. Custom fields are not trivial at all. Adding some regex is peanuts in comparison. 

Please re-consider.

**Comment by tobimori** [comment]
You, as developer/person that implements the plugin, should make sure the experience feels like this for the end editor.
DreamForm is not made to be a "drop-in" plugin. It purposely leaves away stuff to the site developer to implement, so the end user experience is better.

A regex is not trivial to use for an editor.

**Comment by tobimori** [comment]
If you have any issues following the custom field guide from the docs, please let me know. So far I have only received postive feedback for it. Extendability is a first-class citizen for DreamForm the same way as it is for Kirby.
