### ISSUE TITLE
Sending E-Mail fails when credentials are not a valid email address

### ISSUE THREAD

**Issue by sciloqi** [tobimori/kirby-dreamform#82]
I get the response "'placeholder' is not a valid email address" when the credentials are not an email address.

My kirby configuration looks like this:

```
email' => [
  'transport' => [
    'username' => 'placeholder',
```

Testing with a username like 'placeholder@domain.tld' works, but I need a simple username.

**Comment by tobimori** [comment]
You can use `tobimori.dreamform.actions.email.from.email`
