### ISSUE TITLE
Email HTML Templates not working when using Laravel Blade Plugin (leitsch/kirby-blade:3.0.2)

### ISSUE THREAD

**Issue by nerdcel** [tobimori/kirby-dreamform#84]
The default HTML Email does not work when the Blade Plugin is installed.
Temp. moving the plugin outside the plugin folder, so it does not load, makes the HTML Emails work.

If I try to overwrite the default Templates and name them:

- /site/templates/emails/dreamform.blade.php
- /site/templates/emails/dreamform.html.blade.php

I get the Error: Undefined array key "kirby"

<img width="468" alt="Bildschirmfoto" src="https://github.com/user-attachments/assets/9b24b95f-ea2a-440c-8fed-83d7f7e73ebc">

**Comment by tobimori** [comment]
Please create an issue at the Blade plugin repo for this.

**Comment by nerdcel** [comment]
I am not sure if it is a issue on the blade plugin side. 
When I try to use the default template without overriding it using a blade file, the HTML part of the email gets rendered using the plaintext template.
But that looks weird, because of the missing linebreaks. It simply skips the html template.

**Comment by tobimori** [comment]
Well, the Blade plugin rewrites the template logic. I assume it skips over the .html part and doesn't wire it correctly to the built-in logic. This was the same case with the snippets with slots that I wrote a PR for in the past.

**Comment by nerdcel** [comment]
@tobimori thanks for the hint.
I made a PR and that would fix the problem: [PR](https://github.com/lukasleitsch/kirby-blade/pull/39)
