### ISSUE TITLE
.MP3 audio file not uploaded?

### ISSUE THREAD

**Issue by Matoseb** [tobimori/kirby-dreamform#85]
small .mp3 file not appearing anywhere after upload.
No errors thrown.
Other types such as pdf, images, zip works though.

Tested on
- Mac OS, Chrom 127
- replicated on the dreamform plainkit
- File field set to accept anything

**Comment by tobimori** [comment]
I can reproduce this error. It seems like Kirby rejects the file creation with `Invalid file type: -` error. However, uploading an mp3 file to the panel (which should trigger the same error) seems to work.

**Comment by tobimori** [comment]
Fixed in next minor release
