### ISSUE TITLE
FormPage hidden field error

### ISSUE THREAD

**Issue by Matoseb** [tobimori/kirby-dreamform#86]
Hi,
Using the [hidden field](https://plugins.andkindness.com/dreamform/docs/fields/hidden) with a searchquery throws me an error:

```json
{
  "status":"error","exception":"Error","code":0,"message":
  "Call to protected method tobimori\\DreamForm\\Fields\\Field::sanitize() from scope tobimori\\DreamForm\\Models\\FormPage",
  "details":null,
  "file":"..\/site\/plugins\/kirby-dreamform\/classes\/Models\/FormPage.php",
  "line":465
}
```

I tried to convert the Field::sanitize() to public, but this crashes the whole kirby.
I disabled the function for now since it's not currently doing anything.

**Comment by tobimori** [comment]
Can confirm, but a) not sure what I actually thought of here when marking the methods as protected, and b) not sure how to solve this without a breaking change for all custom fields that have a sanitze method 😓
