### ISSUE TITLE
Ability to have links to files in mail

### ISSUE THREAD

**Issue by Matoseb** [tobimori/kirby-dreamform#89]
Hi, is there a way to have a link to the uploaded files in a mail template?
A client wants to access the files directly from the mail without logging in to Kirby.

I can have the file names but the field value doesn't seem to have the url inside:

```php

if($field::type() === "file-upload") {
  $fileArray = $field->value()->value();
  echo implode(", ", array_map(fn($file) => "{$file['name']}", $fileArray));
}

```

**Comment by tobimori** [comment]
You should be able to access the file object using the submision, something like `$submission->valueForId($field->id())->toFile()`

**Comment by Matoseb** [comment]
Ah it seems the file is in a temporary state

```[{"name":"gradient_00.png","full_path":"gradient_00.png","type":"image\/png","tmp_name":"\/private\/var\/folders\/gw\/9s1_3_nn0r79dpqf536_zhk00000gn\/T\/phpBFZSjs","error":0,"size":894}]```

I don't have access to the file yet, it gives me null

**Comment by tobimori** [comment]
You're right, the game only saves the file after actions have been sent, so it's not possible to get the file URL in the Email action.

**Comment by tobimori** [comment]
My suggestion would be to add an API route that uses the UUID of the submission and filename to find the file and return it.

**Comment by Matoseb** [comment]
100% agree, I will try this

**Comment by tobimori** [comment]
1.5.0-rc.2 can have files uploaded as attachments: https://github.com/tobimori/kirby-dreamform/releases/tag/1.5.0-rc.2
