### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [tobimori/kirby-dreamform#95]
The hidden field used as the honeypot doesn't have a label and therefore fails the Lighthouse audit test.

Could a hidden label be added so the test passes? Or would this reduce the effectiveness of the honeypot? Thanks

**Comment by tobimori** [comment]
You can disable the Honeypot if necessary: https://plugins.andkindness.com/dreamform/docs/guards/what-are-guards
or override the snippet.

**Comment by gitlabisbetterthangithub** [comment]
Looking at the docs for the [aria-hidden attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden#values), it seems to require a boolean value, otherwise you leave it up to the user agent to determine whether it is rendered. I set it to true and then re-ran the Lighthouse test and the message went away.

So I propose the fixes in #96. No need for a label :)
